#!/usr/bin/env perl

##########################################################################
##                                                             
##         FILE: ssl4curl
##        USAGE: Add to your ~/.bashrc or export from command line
##               export `ssl4curl`
##  DESCRIPTION: Download and setup Mozilla certificates for curl SSL/TLS
##
##      OPTIONS:  -h for help
##                -l to list export string
##                -i initialize
## REQUIREMENTS:  perl
##         BUGS:  ---
##        NOTES:  ---
##       AUTHOR:  Zdenek Bohunek (z448), zed448@icloud.com
##      COMPANY:  load.sh laboratory
##      VERSION:  1.0
##      CREATED:  05/25/2016 09:34:33
##     REVISION:  ---
##########################################################################

use warnings;
use strict;

use Getopt::Std;
use Cwd;
use Config;
use open qw<:encoding(UTF-8)>;

my( %option, $mozilla_ca_path, $mk_ca_bundle_script ) = ();
my $CURL_CA_BUNDLE = '';
getopts('hpi', \%option);

# setup cpan
$ENV{PERL_MM_USE_DEFAULT}=1;

sub install_ca {
# use cpan to install Mozilla::CA
    system("perl -MCPAN -e 'install Mozilla::CA'");
    my $status = `perldoc -l Mozilla::CA`;
    return 0 unless $status =~ /\:\:CA/;
}

sub get_ca {
# find Mozilla::CA installed path 
    open my $pipe,"-|", 'perldoc -l Mozilla::CA';
    while(<$pipe>){ $mozilla_ca_path = $_ }
    close $pipe;

# find path to mk-ca-bundle.pl
    $mk_ca_bundle_script = $mozilla_ca_path;
    $mk_ca_bundle_script =~ s/(.*)(\/CA\.pm)/$1/;
    $mk_ca_bundle_script = $1;
    $mk_ca_bundle_script = "$mk_ca_bundle_script" . '/' . 'mk-ca-bundle.pl';

# execute mk-ca-bundle.pl to download certificates
    open $pipe,"-|", "$mk_ca_bundle_script 2>&1";
    close $pipe;

# find path to created cacert.pem
    my $cwd = getcwd();
    chomp $mozilla_ca_path;
    $mozilla_ca_path =~ s/(.*)(\.pm)/$1/;
# make export string
    $CURL_CA_BUNDLE = $mozilla_ca_path . '/' . 'cacert.pem';
}

if(defined $option{p}){ 
    print "export CURL_CA_BUNDLE=$CURL_CA_BUNDLE" if get_ca();
} elsif(defined $option{i}){
    my $id = `id`;
    die "initialization has to be run as 'root'" unless $id =~ /root/;
    print "initialized\n" if install_ca();
} elsif(defined $option{h}){
    system("perldoc $0");
    die;
} else {
    print "CURL_CA_BUNDLE=$CURL_CA_BUNDLE\n" if get_ca();
}

=head1 NAME 

=over 12

=item ssl4curl

=back

=head1 SYNOPSIS

=over 12

=item Download and setup Mozilla certificates for curl SSL/TLS

=item aka fix for error bellow

curl: (60) SSL certificate problem: unable to get local issuer certificate

=back

=head1 INSTALLATION

=over 12

=item clone repository

git clone https://github.com/z448/ssl4curl

=item initialize from command line as root or use sudo

sudo ssl4curl -i

=back 

=head1 USAGE

=over 12 

- add to ~/.bashrc to check/download and setup certificates on start of every session

C<export `ssl4curl -p`>

- execute on command line to check/download certificates and list export string. You can add output string into your ~/.bashrc in which case certificate setup will be skiped on start of session.

C<ssl4curl>

- print this pod

C<ssl4curl -h>

=back

=cut





